import Foundation
import StockPlanShared
import Vapor

typealias AuthRegisterRequest = StockPlanShared.AuthRegisterRequest
typealias AuthLoginRequest = StockPlanShared.AuthLoginRequest
typealias AuthResponse = StockPlanShared.AuthResponse
typealias AuthRegisterResponse = StockPlanShared.AuthRegisterResponse
typealias AuthUserResponse = StockPlanShared.AuthUserResponse
typealias AuthForgotPasswordRequest = StockPlanShared.AuthForgotPasswordRequest
typealias AuthForgotPasswordResponse = StockPlanShared.AuthForgotPasswordResponse
typealias AuthResetPasswordRequest = StockPlanShared.AuthResetPasswordRequest
typealias AuthRefreshRequest = StockPlanShared.AuthRefreshRequest
typealias OAuthProvider = StockPlanShared.OAuthProvider
