import Fluent

struct CreateWealthAutomationTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(NetWorthForecastModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("portfolio_list_id", .uuid, .required, .references("portfolio_lists", "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("base_currency", .string, .required)
            .field("horizon_months", .int, .required)
            .field("include_cash", .bool, .required)
            .field("include_crypto", .bool, .required)
            .field("annual_income_growth", .double, .required)
            .field("annual_spending_growth", .double, .required)
            .field("inflation_assumption", .double, .required)
            .field("monthly_income_override", .double)
            .field("monthly_spending_override", .double)
            .field("target_amount", .double)
            .field("path_count", .int, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "user_id", "portfolio_list_id")
            .create()

        try await database.schema(NetWorthForecastRunModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("forecast_id", .uuid, .required, .references(NetWorthForecastModel.schema, "id", onDelete: .cascade))
            .field("status", .string, .required)
            .field("starting_value", .double, .required)
            .field("assumptions", .json, .required)
            .field("timeline", .json, .required)
            .field("target_probability", .double)
            .field("seed", .string, .required)
            .field("failure_reason", .string)
            .field("created_at", .datetime)
            .field("completed_at", .datetime)
            .create()

        try await database.schema(WatchlistScreenModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("watchlist_list_ids", .array(of: .uuid), .required)
            .field("logical_operator", .string, .required)
            .field("groups", .json, .required)
            .field("alerts_enabled", .bool, .required)
            .field("last_evaluated_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(WatchlistScreenEvaluationModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("screen_id", .uuid, .required, .references(WatchlistScreenModel.schema, "id", onDelete: .cascade))
            .field("symbol_count", .int, .required)
            .field("match_symbols", .array(of: .string), .required)
            .field("result", .json, .required)
            .field("is_alert_baseline", .bool, .required)
            .field("evaluated_at", .datetime)
            .create()

        try await database.schema(RebalancingPolicyModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("portfolio_list_id", .uuid, .required, .references("portfolio_lists", "id", onDelete: .cascade))
            .field("base_currency", .string, .required)
            .field("cadence", .string, .required)
            .field("drift_threshold", .double)
            .field("targets", .json, .required)
            .field("enabled", .bool, .required)
            .field("last_confirmed_at", .datetime)
            .field("last_triggered_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "user_id", "portfolio_list_id")
            .create()

        try await database.schema(RebalanceEventModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("policy_id", .uuid, .required, .references(RebalancingPolicyModel.schema, "id", onDelete: .cascade))
            .field("status", .string, .required)
            .field("preview", .json, .required)
            .field("created_at", .datetime)
            .field("confirmed_at", .datetime)
            .field("dismissed_at", .datetime)
            .create()

        try await database.schema(NotificationEventModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("kind", .string, .required)
            .field("deduplication_key", .string, .required)
            .field("title", .string, .required)
            .field("body", .string, .required)
            .field("deep_link", .string)
            .field("payload", .json, .required)
            .field("created_at", .datetime)
            .field("read_at", .datetime)
            .unique(on: "user_id", "deduplication_key")
            .create()

        try await database.schema(NotificationDeliveryModel.schema)
            .id()
            .field("event_id", .uuid, .required, .references(NotificationEventModel.schema, "id", onDelete: .cascade))
            .field("channel", .string, .required)
            .field("status", .string, .required)
            .field("attempt_count", .int, .required)
            .field("last_error", .string)
            .field("next_attempt_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "event_id", "channel")
            .create()

        try await database.schema(AutomationJobLeaseModel.schema)
            .field("name", .string, .identifier(auto: false))
            .field("owner", .string, .required)
            .field("locked_until", .datetime, .required)
            .field("updated_at", .datetime)
            .create()

        try await database.createIndex(on: NetWorthForecastRunModel.schema, columns: ["user_id", "created_at"])
        try await database.createIndex(on: WatchlistScreenModel.schema, columns: ["user_id"])
        try await database.createIndex(on: WatchlistScreenEvaluationModel.schema, columns: ["screen_id", "evaluated_at"])
        try await database.createIndex(on: RebalanceEventModel.schema, columns: ["policy_id", "status"])
        try await database.createIndex(on: NotificationEventModel.schema, columns: ["user_id", "created_at"])
        try await database.createIndex(on: NotificationEventModel.schema, columns: ["user_id", "read_at"])
    }

    func revert(on database: any Database) async throws {
        try await database.schema(AutomationJobLeaseModel.schema).delete()
        try await database.schema(NotificationDeliveryModel.schema).delete()
        try await database.schema(NotificationEventModel.schema).delete()
        try await database.schema(RebalanceEventModel.schema).delete()
        try await database.schema(RebalancingPolicyModel.schema).delete()
        try await database.schema(WatchlistScreenEvaluationModel.schema).delete()
        try await database.schema(WatchlistScreenModel.schema).delete()
        try await database.schema(NetWorthForecastRunModel.schema).delete()
        try await database.schema(NetWorthForecastModel.schema).delete()
    }
}
