import Fluent

struct CreateAIAssistantTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(AIConversation.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("title_encrypted", .data, .required).field("created_at", .datetime)
            .field("updated_at", .datetime).field("expires_at", .datetime, .required)
            .index("user_id", "updated_at").create()
        try await database.schema(AIAssistantMessage.schema).id()
            .field("conversation_id", .uuid, .required, .references(AIConversation.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("role", .string, .required).field("content_encrypted", .data, .required)
            .field("created_at", .datetime).index("conversation_id", "created_at").create()
        try await database.schema(AIAssistantPreference.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("proactive_tips_enabled", .bool, .required, .sql(.default(false)))
            .field("push_enabled", .bool, .required, .sql(.default(false)))
            .field("timezone", .string, .required, .sql(.default("UTC")))
            .field("created_at", .datetime).field("updated_at", .datetime).unique(on: "user_id").create()
        try await database.schema(AIAssistantUsage.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("month_start", .date, .required).field("request_count", .int, .required, .sql(.default(0)))
            .field("created_at", .datetime).field("updated_at", .datetime)
            .unique(on: "user_id", "month_start").create()
        try await database.schema(AIAssistantTip.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("kind", .string, .required).field("title_encrypted", .data, .required)
            .field("body_encrypted", .data, .required).field("importance", .int, .required)
            .field("action_path", .string).field("is_seen", .bool, .required, .sql(.default(false)))
            .field("is_dismissed", .bool, .required, .sql(.default(false)))
            .field("created_at", .datetime).field("expires_at", .datetime, .required)
            .index("user_id", "created_at").create()
        try await database.schema(AIPendingAction.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("conversation_id", .uuid, .references(AIConversation.schema, "id", onDelete: .setNull))
            .field("tool_name", .string, .required).field("arguments_encrypted", .data, .required)
            .field("summary_encrypted", .data, .required).field("status", .string, .required)
            .field("expires_at", .datetime, .required).field("created_at", .datetime)
            .field("updated_at", .datetime).index("user_id", "status").create()
        try await database.schema(AIActionAudit.schema).id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("pending_action_id", .uuid, .required, .references(AIPendingAction.schema, "id", onDelete: .cascade))
            .field("tool_name", .string, .required).field("status", .string, .required)
            .field("details_encrypted", .data).field("created_at", .datetime)
            .index("pending_action_id", "created_at").create()
    }

    func revert(on database: any Database) async throws {
        try await database.schema(AIActionAudit.schema).delete()
        try await database.schema(AIPendingAction.schema).delete()
        try await database.schema(AIAssistantTip.schema).delete()
        try await database.schema(AIAssistantUsage.schema).delete()
        try await database.schema(AIAssistantPreference.schema).delete()
        try await database.schema(AIAssistantMessage.schema).delete()
        try await database.schema(AIConversation.schema).delete()
    }
}
