import Fluent

struct CreateTaxOptimizationTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(Account.schema)
            .field("tax_wrapper", .string)
            .field("tax_jurisdiction", .string)
            .field("tax_owner_member_id", .string)
            .field("lot_selection_method", .string)
            .update()

        try await database.schema(Instrument.schema)
            .field("instrument_type", .string)
            .field("isin", .string)
            .field("cusip", .string)
            .field("tax_identity_group", .string)
            .update()

        try await database.schema("tax_profiles")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("jurisdiction", .string, .required)
            .field("tax_year", .int, .required)
            .field("filing_status", .string, .required)
            .field("reporting_currency", .string, .required)
            .field("profile_json", .string, .required)
            .field("is_complete", .bool, .required)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "user_id", "jurisdiction", "tax_year")
            .create()

        try await database.schema("lot_disposals")
            .id()
            .field("lot_id", .uuid, .required, .references("lots", "id", onDelete: .cascade))
            .field("transaction_id", .uuid, .required, .references("transactions", "id", onDelete: .cascade))
            .field("quantity", .double, .required)
            .field("proceeds", .double, .required)
            .field("cost_basis", .double, .required)
            .field("realized_pnl", .double, .required)
            .field("holding_period", .string, .required)
            .field("created_at", .datetime, .required)
            .unique(on: "lot_id", "transaction_id")
            .create()

        try await database.schema("lot_adjustments")
            .id()
            .field("lot_id", .uuid, .required, .references("lots", "id", onDelete: .cascade))
            .field("source_transaction_id", .uuid, .references("transactions", "id", onDelete: .setNull))
            .field("kind", .string, .required)
            .field("amount", .double, .required)
            .field("quantity", .double)
            .field("currency", .string, .required)
            .field("effective_date", .date, .required)
            .field("metadata_json", .string)
            .field("created_at", .datetime, .required)
            .create()

        try await database.schema("wash_sale_matches")
            .id()
            .field("disposal_id", .uuid, .required, .references("lot_disposals", "id", onDelete: .cascade))
            .field("replacement_lot_id", .uuid, .required, .references("lots", "id", onDelete: .cascade))
            .field("matched_quantity", .double, .required)
            .field("disallowed_loss", .double, .required)
            .field("currency", .string, .required)
            .field("is_permanent", .bool, .required)
            .field("rule_version", .string, .required)
            .field("created_at", .datetime, .required)
            .unique(on: "disposal_id", "replacement_lot_id")
            .create()

        try await database.schema("tax_projection_snapshots")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("profile_id", .uuid, .required, .references("tax_profiles", "id", onDelete: .cascade))
            .field("tax_year", .int, .required)
            .field("jurisdiction", .string, .required)
            .field("rule_version", .string, .required)
            .field("status", .string, .required)
            .field("response_json", .string, .required)
            .field("input_hash", .string, .required)
            .field("generated_at", .datetime, .required)
            .field("created_at", .datetime, .required)
            .create()

        try await database.schema("tax_scenarios")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("profile_id", .uuid, .required, .references("tax_profiles", "id", onDelete: .cascade))
            .field("request_json", .string, .required)
            .field("response_json", .string, .required)
            .field("created_at", .datetime, .required)
            .create()

        try await database.schema("tax_action_plans")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("scenario_id", .uuid, .required, .references("tax_scenarios", "id", onDelete: .cascade))
            .field("idempotency_key", .string, .required)
            .field("status", .string, .required)
            .field("response_json", .string, .required)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "user_id", "idempotency_key")
            .create()

        try await database.schema("tax_notification_preferences")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("enabled", .bool, .required)
            .field("minimum_benefit", .double)
            .field("cooldown_days", .int, .required)
            .field("updated_at", .datetime)
            .unique(on: "user_id")
            .create()

        try await database.schema("tax_notification_deliveries")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("opportunity_id", .string, .required)
            .field("instrument_id", .uuid, .required)
            .field("estimated_benefit", .double, .required)
            .field("currency", .string, .required)
            .field("delivered_at", .datetime, .required)
            .create()

        try await database.schema("tax_reports")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("tax_year", .int, .required)
            .field("kind", .string, .required)
            .field("format", .string, .required)
            .field("status", .string, .required)
            .field("file_path", .string)
            .field("expires_at", .datetime)
            .field("error_message", .string)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .create()

        try await database.schema("tax_projection_jobs")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("tax_year", .int, .required)
            .field("reason", .string, .required)
            .field("idempotency_key", .string, .required)
            .field("status", .string, .required)
            .field("attempt_count", .int, .required)
            .field("next_attempt_at", .datetime, .required)
            .field("last_error", .string)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "idempotency_key")
            .create()

        try await database.createIndex(on: "tax_projection_snapshots", columns: ["user_id", "tax_year", "generated_at"])
        try await database.createIndex(on: "tax_projection_jobs", columns: ["status", "next_attempt_at"])
        try await database.createIndex(on: "tax_notification_deliveries", columns: ["user_id", "instrument_id", "delivered_at"])
    }

    func revert(on database: any Database) async throws {
        for schema in [
            "tax_projection_jobs", "tax_reports", "tax_notification_deliveries",
            "tax_notification_preferences", "tax_action_plans", "tax_scenarios",
            "tax_projection_snapshots", "wash_sale_matches", "lot_adjustments",
            "lot_disposals", "tax_profiles",
        ] {
            try await database.schema(schema).delete()
        }

        try await database.schema(Instrument.schema)
            .deleteField("instrument_type")
            .deleteField("isin")
            .deleteField("cusip")
            .deleteField("tax_identity_group")
            .update()
        try await database.schema(Account.schema)
            .deleteField("tax_wrapper")
            .deleteField("tax_jurisdiction")
            .deleteField("tax_owner_member_id")
            .deleteField("lot_selection_method")
            .update()
    }
}
