import Fluent

struct CreateBankTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema("bank_connections")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("provider", .string, .required)
            .field("institution_id", .string)
            .field("institution_name", .string)
            .field("provider_item_id", .string, .required)
            .field("access_token_enc", .string)
            .field("sync_cursor", .string)
            .field("status", .string, .required)
            .field("consent_expires_at", .datetime)
            .field("last_synced_at", .datetime)
            .field("last_sync_status", .string)
            .field("last_sync_error", .string)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "provider", "provider_item_id")
            .create()
        try await database.createIndex(on: "bank_connections", columns: ["user_id"])

        try await database.schema("bank_accounts")
            .id()
            .field("connection_id", .uuid, .required, .references("bank_connections", "id", onDelete: .cascade))
            .field("provider_account_id", .string, .required)
            .field("name", .string, .required)
            .field("mask", .string)
            .field("currency", .string)
            .field("type", .string)
            .field("balance", .double)
            .field("balance_as_of", .datetime)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "connection_id", "provider_account_id")
            .create()
        try await database.createIndex(on: "bank_accounts", columns: ["connection_id"])

        try await database.schema("bank_transactions")
            .id()
            .field("account_id", .uuid, .required, .references("bank_accounts", "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("provider_tx_id", .string, .required)
            .field("dedupe_hash", .string, .required)
            .field("amount", .double, .required)
            .field("currency", .string)
            .field("occurred_on", .datetime, .required)
            .field("merchant", .string)
            .field("description_text", .string)
            .field("pending", .bool, .required)
            .field("status", .string, .required)
            .field("provider_category", .string)
            .field("expense_id", .uuid)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime)
            .unique(on: "account_id", "provider_tx_id")
            .create()
        try await database.createIndex(on: "bank_transactions", columns: ["user_id", "status"])
    }

    func revert(on database: any Database) async throws {
        try await database.schema("bank_transactions").delete()
        try await database.schema("bank_accounts").delete()
        try await database.schema("bank_connections").delete()
    }
}
