import Fluent
import FluentSQL

struct CreateRebalancingTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(AllocationModelRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("created_by_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .restrict))
            .field("name", .string, .required)
            .field("grouping_mode", .string, .required)
            .field("is_active", .bool, .required)
            .field("revision", .int, .required)
            .field("base_currency", .string, .required)
            .field("default_target_threshold_bps", .int, .required)
            .field("total_threshold_bps", .int, .required)
            .field("fractional_shares_enabled", .bool, .required)
            .field("quantity_increment", .double, .required)
            .field("minimum_trade_amount", .double, .required)
            .field("flat_fee", .double, .required)
            .field("variable_fee_bps", .int, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(AllocationBucketRecord.schema)
            .id()
            .field("model_id", .uuid, .required, .references(AllocationModelRecord.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("target_bps", .int, .required)
            .field("alert_threshold_bps", .int)
            .field("sector_key", .string)
            .field("sort_order", .int, .required)
            .create()

        try await database.schema(AllocationLeafRecord.schema)
            .id()
            .field("model_id", .uuid, .required, .references(AllocationModelRecord.schema, "id", onDelete: .cascade))
            .field("bucket_id", .uuid, .required, .references(AllocationBucketRecord.schema, "id", onDelete: .cascade))
            .field("kind", .string, .required)
            .field("symbol", .string)
            .field("name", .string, .required)
            .field("target_bps", .int, .required)
            .field("alert_threshold_bps", .int)
            .field("sort_order", .int, .required)
            .unique(on: "model_id", "symbol")
            .create()

        try await database.schema(RebalancePlanRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("model_id", .uuid, .required, .references(AllocationModelRecord.schema, "id", onDelete: .restrict))
            .field("created_by_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .restrict))
            .field("model_revision", .int, .required)
            .field("name", .string)
            .field("status", .string, .required)
            .field("base_currency", .string, .required)
            .field("drift_before_bps", .int, .required)
            .field("drift_after_bps", .int, .required)
            .field("total_value", .double, .required)
            .field("estimated_fees", .double, .required)
            .field("estimated_realized_gain_loss", .double, .required)
            .field("simulation_json", .string, .required)
            .field("completion_note", .string)
            .field("exported_at", .datetime)
            .field("completed_at", .datetime)
            .field("cancelled_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(RebalancingAlertRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("model_id", .uuid, .required, .references(AllocationModelRecord.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("scope_id", .string, .required)
            .field("scope_name", .string, .required)
            .field("drift_bps", .int, .required)
            .field("threshold_bps", .int, .required)
            .field("status", .string, .required)
            .field("active_scope_key", .string)
            .field("triggered_at", .datetime, .required)
            .field("acknowledged_at", .datetime)
            .field("resolved_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "active_scope_key")
            .create()

        try await database.schema(RebalancingNotificationPreferenceRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("push_enabled", .bool, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "portfolio_id", "user_id")
            .create()

        try await database.schema(PushDevice.schema)
            .field("capabilities_json", .string, .required, .sql(.default("[]")))
            .update()

        if let sql = database as? any SQLDatabase {
            try await sql.create(index: "allocation_models_portfolio_active_idx")
                .on(AllocationModelRecord.schema)
                .column("portfolio_id")
                .column("is_active")
                .run()
            try await sql.create(index: "rebalance_plans_portfolio_created_idx")
                .on(RebalancePlanRecord.schema)
                .column("portfolio_id")
                .column("created_at")
                .run()
            try await sql.create(index: "rebalancing_alerts_user_status_idx")
                .on(RebalancingAlertRecord.schema)
                .column("user_id")
                .column("status")
                .run()
        }
    }

    func revert(on database: any Database) async throws {
        try await database.schema(PushDevice.schema).deleteField("capabilities_json").update()
        try await database.schema(RebalancingNotificationPreferenceRecord.schema).delete()
        try await database.schema(RebalancingAlertRecord.schema).delete()
        try await database.schema(RebalancePlanRecord.schema).delete()
        try await database.schema(AllocationLeafRecord.schema).delete()
        try await database.schema(AllocationBucketRecord.schema).delete()
        try await database.schema(AllocationModelRecord.schema).delete()
    }
}
