import Fluent
import FluentSQL

struct CreatePortfolioManagementAndReportingTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(PortfolioList.schema)
            .field("purpose", .string, .required, .sql(.default("personal")))
            .field("ownership", .string, .required, .sql(.default("individual")))
            .field("mode", .string, .required, .sql(.default("actual")))
            .field("base_currency", .string, .required, .sql(.default("USD")))
            .field("source_portfolio_id", .uuid, .references(PortfolioList.schema, "id", onDelete: .setNull))
            .field("cloned_at", .datetime)
            .field("archived_at", .datetime)
            .update()

        try await database.schema(Account.schema)
            .field("portfolio_id", .uuid, .references(PortfolioList.schema, "id", onDelete: .restrict))
            .update()

        try await database.schema(PortfolioMembershipRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("role", .string, .required)
            .field("status", .string, .required)
            .field("joined_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "portfolio_id", "user_id")
            .create()

        try await database.schema(PortfolioInvitationRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("email", .string, .required)
            .field("role", .string, .required)
            .field("status", .string, .required)
            .field("token_hash", .string, .required)
            .field("expires_at", .datetime, .required)
            .field("accepted_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "token_hash")
            .create()

        try await database.schema(PortfolioCashPositionRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("label", .string, .required)
            .field("currency", .string, .required)
            .field("balance", .double, .required)
            .field("as_of", .datetime, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(RetirementPlanRecord.schema)
            .id()
            .field("portfolio_id", .uuid, .required, .references(PortfolioList.schema, "id", onDelete: .cascade))
            .field("rule_version", .string, .required)
            .field("input_json", .string, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "portfolio_id")
            .create()

        try await database.schema(AdvancedReportTemplateRecord.schema)
            .id()
            .field("owner_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("input_json", .string, .required)
            .field("revision", .int, .required)
            .field("is_starter_template", .bool, .required)
            .field("archived_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(AdvancedReportScheduleRecord.schema)
            .id()
            .field("owner_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("input_json", .string, .required)
            .field("next_run_at", .datetime)
            .field("last_run_at", .datetime)
            .field("paused_reason", .string)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(AdvancedReportRunRecord.schema)
            .id()
            .field("template_id", .uuid, .required, .references(AdvancedReportTemplateRecord.schema, "id", onDelete: .restrict))
            .field("schedule_id", .uuid, .references(AdvancedReportScheduleRecord.schema, "id", onDelete: .setNull))
            .field("requested_by_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("template_revision", .int, .required)
            .field("template_input_json", .string, .required)
            .field("output_formats_json", .string, .required)
            .field("recipient_user_ids_json", .string, .required)
            .field("status", .string, .required)
            .field("scheduled_for", .datetime)
            .field("claimed_at", .datetime)
            .field("started_at", .datetime)
            .field("completed_at", .datetime)
            .field("failure_reason", .string)
            .field("attempt_count", .int, .required)
            .field("retry_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(AdvancedReportArtifactRecord.schema)
            .id()
            .field("run_id", .uuid, .required, .references(AdvancedReportRunRecord.schema, "id", onDelete: .cascade))
            .field("format", .string, .required)
            .field("filename", .string, .required)
            .field("content_type", .string, .required)
            .field("size_bytes", .int64, .required)
            .field("sha256", .string, .required)
            .field("storage_key", .string, .required)
            .field("expires_at", .datetime, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema(AdvancedReportDeliveryRecord.schema)
            .id()
            .field("run_id", .uuid, .required, .references(AdvancedReportRunRecord.schema, "id", onDelete: .cascade))
            .field("recipient_user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("recipient_email", .string, .required)
            .field("status", .string, .required)
            .field("attempt_count", .int, .required)
            .field("last_attempt_at", .datetime)
            .field("delivered_at", .datetime)
            .field("failure_reason", .string)
            .field("link_expires_at", .datetime)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "run_id", "recipient_user_id")
            .create()

        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw("""
        UPDATE accounts AS account
        SET portfolio_id = (
            SELECT id
            FROM portfolio_lists
            WHERE user_id = account.user_id AND mode = 'actual'
            ORDER BY is_default DESC, created_at ASC
            LIMIT 1
        )
        WHERE account.portfolio_id IS NULL
        """).run()
        try await sql.raw("CREATE INDEX portfolio_memberships_user_status_idx ON portfolio_memberships (user_id, status)").run()
        try await sql.raw("CREATE INDEX portfolio_invitations_email_status_idx ON portfolio_invitations (LOWER(email), status)").run()
        try await sql.raw("CREATE INDEX advanced_report_runs_status_retry_idx ON advanced_report_runs (status, retry_at, created_at)").run()
        try await sql.raw("CREATE INDEX advanced_report_artifacts_expiry_idx ON advanced_report_artifacts (expires_at)").run()
        try await sql.raw("CREATE INDEX advanced_report_schedules_due_idx ON advanced_report_schedules (next_run_at) WHERE paused_reason IS NULL").run()
    }

    func revert(on database: any Database) async throws {
        try await database.schema(AdvancedReportDeliveryRecord.schema).delete()
        try await database.schema(AdvancedReportArtifactRecord.schema).delete()
        try await database.schema(AdvancedReportRunRecord.schema).delete()
        try await database.schema(AdvancedReportScheduleRecord.schema).delete()
        try await database.schema(AdvancedReportTemplateRecord.schema).delete()
        try await database.schema(RetirementPlanRecord.schema).delete()
        try await database.schema(PortfolioCashPositionRecord.schema).delete()
        try await database.schema(PortfolioInvitationRecord.schema).delete()
        try await database.schema(PortfolioMembershipRecord.schema).delete()
        try await database.schema(Account.schema).deleteField("portfolio_id").update()
        try await database.schema(PortfolioList.schema)
            .deleteField("archived_at")
            .deleteField("cloned_at")
            .deleteField("source_portfolio_id")
            .deleteField("base_currency")
            .deleteField("mode")
            .deleteField("ownership")
            .deleteField("purpose")
            .update()
    }
}
