import Fluent
import FluentSQL

struct CreateBudgetingEngineTables: AsyncMigration {
    func prepare(on database: any Database) async throws {
        try await database.schema(BudgetSnapshot.schema)
            .field("currency_code", .string, .required, .sql(.default("USD")))
            .field("category_drift_threshold", .double, .required, .sql(.default(15)))
            .field("total_drift_threshold", .double, .required, .sql(.default(10)))
            .field("alerts_enabled", .bool, .required, .sql(.default(true)))
            .field("alert_on_unbudgeted", .bool, .required, .sql(.default(true)))
            .field("revision", .int, .required, .sql(.default(0)))
            .update()

        try await database.schema(BudgetPlanItem.schema)
            .field("target_type", .string, .required, .sql(.default("fixed")))
            .field("income_percentage", .double)
            .field("threshold_override", .double)
            .field("allocation_kind", .string, .required, .sql(.default("expense")))
            .field("reallocation_eligible", .bool, .required, .sql(.default(false)))
            .field("destination_financial_goal_id", .uuid, .references(FinancialGoalModel.schema, "id", onDelete: .setNull))
            .field("destination_portfolio_list_id", .uuid, .references(PortfolioList.schema, "id", onDelete: .setNull))
            .update()

        try await database.schema(Expense.schema)
            .field("notes", .string)
            .field("receipt_metadata", .json)
            .update()

        try await database.schema(BudgetDriftAlertState.schema)
            .id()
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("snapshot_id", .uuid, .required, .references(BudgetSnapshot.schema, "id", onDelete: .cascade))
            .field("scope_key", .string, .required)
            .field("level", .string, .required)
            .field("breach_sequence", .int, .required, .sql(.default(0)))
            .field("last_notified_level", .string)
            .field("last_notified_at", .datetime)
            .field("evaluated_at", .datetime)
            .field("cleared_at", .datetime)
            .unique(on: "snapshot_id", "scope_key")
            .create()

        try await database.schema(BudgetReallocationEventModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("request_id", .uuid, .required)
            .field("source_snapshot_id", .uuid, .required, .references(BudgetSnapshot.schema, "id", onDelete: .cascade))
            .field("target_snapshot_id", .uuid, .required, .references(BudgetSnapshot.schema, "id", onDelete: .cascade))
            .field("effective_month", .date, .required)
            .field("freed_capital", .double, .required)
            .field("financial_goal_id", .uuid, .references(FinancialGoalModel.schema, "id", onDelete: .setNull))
            .field("portfolio_list_id", .uuid, .references(PortfolioList.schema, "id", onDelete: .setNull))
            .field("adjustments", .json, .required)
            .field("created_at", .datetime)
            .unique(on: "user_id", "request_id")
            .create()

        try await database.schema(BudgetTemplateModel.schema)
            .id()
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("items", .json, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .unique(on: "user_id", "name")
            .create()

        try await database.createIndex(on: BudgetDriftAlertState.schema, columns: ["user_id", "level"])
        try await database.createIndex(on: BudgetReallocationEventModel.schema, columns: ["user_id", "created_at"])
        try await database.createIndex(on: BudgetTemplateModel.schema, columns: ["user_id"])
        try await database.createIndex(on: Expense.schema, columns: ["user_id", "occurred_on", "category_id"])
    }

    func revert(on database: any Database) async throws {
        try await database.deleteIndex(on: Expense.schema, columns: ["user_id", "occurred_on", "category_id"])
        try await database.schema(BudgetTemplateModel.schema).delete()
        try await database.schema(BudgetReallocationEventModel.schema).delete()
        try await database.schema(BudgetDriftAlertState.schema).delete()
        try await database.schema(Expense.schema).deleteField("notes").deleteField("receipt_metadata").update()
        try await database.schema(BudgetPlanItem.schema)
            .deleteField("target_type").deleteField("income_percentage").deleteField("threshold_override")
            .deleteField("allocation_kind").deleteField("reallocation_eligible")
            .deleteField("destination_financial_goal_id").deleteField("destination_portfolio_list_id")
            .update()
        try await database.schema(BudgetSnapshot.schema)
            .deleteField("currency_code").deleteField("category_drift_threshold")
            .deleteField("total_drift_threshold").deleteField("alerts_enabled")
            .deleteField("alert_on_unbudgeted").deleteField("revision")
            .update()
    }
}
