import Vapor
import StockPlanShared

typealias BrokerConnectionResponse = StockPlanShared.BrokerConnectionResponse
typealias BrokerHoldingResponse = StockPlanShared.BrokerHoldingResponse
typealias BrokerSyncResponse = StockPlanShared.BrokerSyncResponse
