import Vapor
import StockPlanShared

typealias DashboardResponse = StockPlanShared.DashboardResponse
typealias DashboardPerformerDTO = StockPlanShared.DashboardPerformerDTO
typealias DashboardAllocationDTO = StockPlanShared.DashboardAllocationDTO
