@testable import StockPlanBackend
import VaporTesting
import Testing

@Suite("OpenAPI Docs Tests")
struct OpenAPIDocsTests {
    @Test("OpenAPI spec includes health, stock valuation, and UserProfile endpoints and schemas")
    func docsAreBundled() async throws {
        let app = try await Application.make(.testing)
        do {
            try await configure(app)

            try await app.testing().test(.GET, "openapi.yaml", afterResponse: { res async in
                #expect(res.status == .ok)
                #expect(res.headers.first(name: .contentType) == "application/yaml; charset=utf-8")

                let body = res.body.string
                #expect(body.contains("/health:"))
                #expect(body.contains("operationId: health"))
                #expect(body.contains("HealthResponse:"))
                #expect(body.contains("/v1/market/details:"))
                #expect(body.contains("/v1/market/history:"))
                #expect(body.contains("/v1/market/history/archive:"))
                #expect(body.contains("/v1/market/history/archive/sync:"))
                #expect(body.contains("/v1/market/news:"))
                #expect(body.contains("/v1/market/news/archive:"))
                #expect(body.contains("/v1/market/news/archive/sync:"))
                #expect(body.contains("/v1/market/basic-financials/{symbol}:"))
                #expect(body.contains("/v1/market/compare:"))
                #expect(body.contains("/v1/market/analysis/{symbol}:"))
                #expect(body.contains("/v1/market/cash-flow-statement/{symbol}:"))
                #expect(body.contains("/v1/market/balance-sheet-statement/{symbol}:"))
                #expect(body.contains("/v1/market/ratios-ttm/{symbol}:"))
                #expect(body.contains("/v1/market/grades-consensus/{symbol}:"))
                #expect(body.contains("/v1/market/financial-growth/{symbol}:"))
                #expect(body.contains("/v1/market/earnings/{symbol}:"))
                #expect(body.contains("/v1/market/earnings-calendar:"))
                #expect(body.contains("/v1/market/analyst-estimates/{symbol}:"))
                #expect(body.contains("/v1/market/ratios/{symbol}:"))
                #expect(body.contains("/v1/market/historical-sector-performance:"))
                #expect(body.contains("operationId: getMarketDetails"))
                #expect(body.contains("operationId: getMarketHistory"))
                #expect(body.contains("operationId: getArchivedMarketHistory"))
                #expect(body.contains("operationId: syncArchivedMarketHistory"))
                #expect(body.contains("operationId: getMarketNews"))
                #expect(body.contains("operationId: getArchivedMarketNews"))
                #expect(body.contains("operationId: syncArchivedMarketNews"))
                #expect(body.contains("operationId: getBasicFinancials"))
                #expect(body.contains("operationId: getMarketCompare"))
                #expect(body.contains("operationId: getMarketAnalysis"))
                #expect(body.contains("operationId: getCashFlowStatement"))
                #expect(body.contains("operationId: getBalanceSheetStatement"))
                #expect(body.contains("operationId: getRatiosTTM"))
                #expect(body.contains("operationId: getGradesConsensus"))
                #expect(body.contains("operationId: getFinancialGrowth"))
                #expect(body.contains("operationId: getMarketEarnings"))
                #expect(body.contains("operationId: getMarketEarningsCalendar"))
                #expect(body.contains("operationId: getAnalystEstimates"))
                #expect(body.contains("operationId: getRatios"))
                #expect(body.contains("operationId: getHistoricalSectorPerformance"))
                #expect(body.contains("Premium or paid FMP plan required for this symbol"))
                #expect(body.contains("Market data provider unavailable or misconfigured"))
                #expect(body.contains("Market news provider unavailable or misconfigured"))
                #expect(body.contains("If market data is disabled"))
                #expect(body.contains("MARKET_PROVIDER=finnhub"))
                #expect(body.contains("FINNHUB_API_KEY"))
                #expect(body.contains("FMP_API_KEY"))
                #expect(body.contains("FMP_SYMBOL_ACCESS_TIER"))
                #expect(body.contains("FINNHUB_WEBHOOK_URL"))
                #expect(body.contains("FINNHUB_WEBHOOK_SECRET"))
                #expect(body.contains("/webhooks/finnhub/news:"))
                #expect(body.contains("operationId: finnhubNewsWebhook"))
                #expect(body.contains("X-Finnhub-Secret"))
                #expect(body.contains("StockDetailsResponse:"))
                #expect(body.contains("StockHistory:"))
                #expect(body.contains("StockNews:"))
                #expect(body.contains("BasicFinancialsResponse:"))
                #expect(body.contains("BasicFinancialSeriesPoint:"))
                #expect(body.contains("StockAnalysisMetricsResponse:"))
                #expect(body.contains("CashFlowStatementResponse:"))
                #expect(body.contains("BalanceSheetStatementResponse:"))
                #expect(body.contains("RatiosTTMResponse:"))
                #expect(body.contains("GradesConsensusResponse:"))
                #expect(body.contains("FinancialGrowthResponse:"))
                #expect(body.contains("AnalystEstimatesResponse:"))
                #expect(body.contains("RatiosResponse:"))
                #expect(body.contains("HistoricalSectorPerformanceResponse:"))
                #expect(body.contains("operationId: finnhubQuote"))
                #expect(body.contains("operationId: finnhubSearch"))
                #expect(body.contains("operationId: finnhubCompanyNews"))
                #expect(body.contains("operationId: finnhubBasicFinancials"))
                #expect(body.contains("operationId: finnhubStockCandles"))
                #expect(body.contains("operationId: finnhubCompanyProfile2"))
                #expect(body.contains("operationId: finnhubForexRates"))
                #expect(body.contains("operationId: fmpCashFlowStatement"))
                #expect(body.contains("operationId: fmpBalanceSheetStatement"))
                #expect(body.contains("operationId: fmpRatiosTTM"))
                #expect(body.contains("operationId: fmpGradesConsensus"))
                #expect(body.contains("operationId: fmpFinancialGrowth"))
                #expect(body.contains("operationId: fmpHistoricalSectorPerformance"))
                #expect(body.contains("finnhubQueryToken:"))
                #expect(body.contains("finnhubHeaderToken:"))
                #expect(body.contains("fmpQueryApiKey:"))
                #expect(body.contains("finnhubWebhookSecretHeader:"))
                #expect(body.contains("finnhubWebhookSecretQuery:"))
                #expect(body.contains("X-Finnhub-Token"))
                #expect(body.contains("/v1/stocks/symbol/{symbol}/valuation:"))
                #expect(body.contains("operationId: getStockValuation"))
                #expect(body.contains("operationId: createStockValuation"))
                #expect(body.contains("operationId: updateStockValuation"))
                #expect(body.contains("authenticated user's stock"))
                #expect(body.contains("must already exist in the authenticated user's portfolio"))
                #expect(body.contains("PriceRange:"))
                #expect(body.contains("StockValuationRequest:"))
                #expect(body.contains("/v1/users:"))
                #expect(body.contains("/v1/users/{id}:"))
                #expect(body.contains("operationId: getUserProfile"))
                #expect(body.contains("operationId: updateUserProfile"))
                #expect(body.contains("operationId: deleteUserProfile"))
                #expect(body.contains("operationId: getUserProfileByID"))
                #expect(body.contains("operationId: updateUserProfileByID"))
                #expect(body.contains("operationId: deleteUserProfileByID"))
                #expect(body.contains("UserProfile:"))
                #expect(body.contains("UpdateUserProfileRequest:"))
                #expect(body.contains("DeleteUserProfileResponse:"))
            })
        } catch {
            try await app.asyncShutdown()
            throw error
        }

        try await app.asyncShutdown()
    }
}
