apiVersion: 1

datasources:
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: true
    editable: false
  - name: OTel Collector Metrics
    uid: otel-collector-metrics
    type: prometheus
    access: proxy
    url: http://otel-collector:9464
    editable: false
