import Vapor
import StockPlanShared

typealias StockDetailsResponse = StockPlanShared.StockDetailsResponse
typealias QuoteResponse = StockPlanShared.QuoteResponse
typealias CompanyProfileResponse = StockPlanShared.CompanyProfileResponse
typealias PriceBarResponse = StockPlanShared.PriceBarResponse
typealias HistoryResponse = StockPlanShared.HistoryResponse
typealias SearchResultResponse = StockPlanShared.SearchResultResponse
typealias FxRateResponse = StockPlanShared.FxRateResponse
typealias QuoteBatchResponse = StockPlanShared.QuoteBatchResponse
