import StockPlanShared

typealias AllocationItem = StockPlanShared.AllocationItem
typealias PortfolioSummaryResponse = StockPlanShared.PortfolioSummaryResponse
typealias PerformancePoint = StockPlanShared.PerformancePoint
typealias PortfolioPerformanceResponse = StockPlanShared.PortfolioPerformanceResponse
typealias TransactionResponse = StockPlanShared.TransactionResponse
typealias LotResponse = StockPlanShared.LotResponse
typealias PnlBySymbol = StockPlanShared.PnlBySymbol
typealias PnlResponse = StockPlanShared.PnlResponse
