import StockPlanShared
import Vapor

extension StockRequest: @retroactive Content {}
extension StockResponse: @retroactive Content {}
extension WatchlistItemRequest: @retroactive Content {}
extension WatchlistItemUpdateRequest: @retroactive Content {}
extension WatchlistItemResponse: @retroactive Content {}
extension ResearchNoteRequest: @retroactive Content {}
extension ResearchNoteResponse: @retroactive Content {}
extension PriceRange: @retroactive Content {}
extension StockValuationRequest: @retroactive Content {}
extension StockHistory: @retroactive Content {}
extension StockNews: @retroactive Content {}
extension BulkStockRequest: @retroactive Content {}
extension BulkStockResultItem: @retroactive Content {}
extension BulkStockResponse: @retroactive Content {}

extension PortfolioSummaryResponse: @retroactive Content {}
extension PortfolioPerformanceResponse: @retroactive Content {}
extension TransactionResponse: @retroactive Content {}
extension LotResponse: @retroactive Content {}
extension PnlResponse: @retroactive Content {}

extension UserProfile: @retroactive Content {}
extension GetUserProfileRequest: @retroactive Content {}
extension GetUserProfileResponse: @retroactive Content {}
extension UpdateUserProfileRequest: @retroactive Content {}
extension UpdateUserProfileResponse: @retroactive Content {}
extension DeleteUserProfileRequest: @retroactive Content {}
extension DeleteUserProfileResponse: @retroactive Content {}
extension EmptyAPIResponse: @retroactive Content {}
extension QuoteResponse: @retroactive Content {}
extension StockValuationDraft: @retroactive Content {}
extension AuthResponse: @retroactive Content {}
extension AuthForgotPasswordResponse: @retroactive Content {}
extension DashboardSummaryResponse: @retroactive Content {}
extension MarketOverviewResponse: @retroactive Content {}
extension SectorPerformanceResponse: @retroactive Content {}
extension EconomicEventResponse: @retroactive Content {}
extension StockDetailsResponse: @retroactive Content {}
extension CompanyProfileResponse: @retroactive Content {}
extension PriceBarResponse: @retroactive Content {}
extension HistoryResponse: @retroactive Content {}
extension SearchResultResponse: @retroactive Content {}
extension FxRateResponse: @retroactive Content {}
extension QuoteBatchResponse: @retroactive Content {}
extension BrokerDTO: @retroactive Content {}
extension BrokerConnectionDTO: @retroactive Content {}
extension CsvImportRequest: @retroactive Content {}
extension CsvImportResponse: @retroactive Content {}
extension BrokerSyncRequest: @retroactive Content {}
extension BrokerSyncResponse: @retroactive Content {}
extension BrokerAccountDTO: @retroactive Content {}
extension BrokerTransactionDTO: @retroactive Content {}
extension BrokerPositionDTO: @retroactive Content {}
extension StatisticsSummaryResponse: @retroactive Content {}
extension MetricHistoryResponse: @retroactive Content {}
extension MetricPoint: @retroactive Content {}
extension MetricGrowth: @retroactive Content {}
extension ValuationMetricsResponse: @retroactive Content {}
extension PeerComparisonResponse: @retroactive Content {}
extension RecommendationTrendResponse: @retroactive Content {}
extension TargetPriceResponse: @retroactive Content {}
extension SentimentResponse: @retroactive Content {}
extension TechnicalIndicatorsResponse: @retroactive Content {}
extension EarningsCalendarResponse: @retroactive Content {}
extension EarningsCalendarItem: @retroactive Content {}

